### ISSUE TITLE
How to inject dll？

### ISSUE THREAD

**Issue by q1435153841** [tostercx/GTAO_Booster_PoC#17]
Can I just simply put dll in root directory？

**Comment by liuziangexit** [comment]
Inject dll means you load the library into the program's address space without getting noticed. So simply put the dll file into the GTA directory wont help.

I suggest use this one: https://github.com/DarthTon/Xenos/releases/tag/2.3.2
This is an open source injector and is easy to use.

**Comment by douglasb78** [comment]
Use Xenos Injector w/ manual map and 20 delay.

**Comment by q1435153841** [comment]
> Inject dll means you load the library into the program's address space without getting noticed. So simply put the dll file into the GTA directory wont help.
> 
> I suggest use this one: https://github.com/DarthTon/Xenos/releases/tag/2.3.2
> This is an open source injector and is easy to use.
