### ISSUE TITLE
How build DLL?...

### ISSUE THREAD

**Issue by x1z53** [tostercx/GTAO_Booster_PoC#18]
I know how inject, but I just don't know how to build DLL

**Comment by patrickvrl** [comment]
Search it on YouTube. It's very easy, but you need the right program to do it

**Comment by liuziangexit** [comment]
just press F7

**Comment by x1z53** [comment]
1. Open '.sln' file
2. **'Build' -> 'Batch Build...' -> 'Select All' -> 'Build'**

For people who face it like me

**Comment by x1z53** [comment]
Thanks, guys
