### ISSUE TITLE
Possible Rockstar Launcher version.

### ISSUE THREAD

**Issue by miloscosovic11** [tostercx/GTAO_Booster_PoC#2]
Sorry if im bothering with this, but I was wondering if it were possible to make a RL version of this DLL?

**Comment by miloscosovic11** [comment]
Or further more, could this existing DLL be used for the RL version of the game without further modifications to it.

**Comment by tostercx** [comment]
RL = retail version? No, it won't work out of the box - the function addresses are hard-coded for just Steam.

Yes, it would be possible to either manually find them or use pattern matching to make a more generic version. I don't plan to do it, it's a lot of work and I only wanted to get the word out. Not to mention distributing mods for online games can get you sued in some cases (I believe this only applies to selling cheats, IANAL).

Hopefully R* fixes it. If not, there are plenty of mod/cheat developing communities that could pick this up :)

**Comment by miloscosovic11** [comment]
"RL = retail version?" I meant rockstar launcher version

**Comment by tostercx** [comment]
Ah. Yeah, same thing. Won't work with any other versions, nether that nor the Epic Games store one.

**Comment by miloscosovic11** [comment]
Ah that sucks, well its a great find either way, lets just hope rockstar actually does something for the community with this instead of just lining their pockets with pure cash.

**Comment by QuickNET-Tech** [comment]
> Hopefully R* fixes it. If not, there are plenty of mod/cheat developing communities that could pick this up :)  

They already have ;)

Good work on this btw, many thanks! Hopefully this being shared around and picked up by gaming/news sites will get R*'s attention. No one should need cheats to not have obscene load times.

**Comment by deton24** [comment]
> They already have ;)

Any more info on that?

**Comment by rfoodxmodz** [comment]
**Anyone here have download link gta5.exe (1.53) for steam?**

I want to port it to R* Launcher Version

**Comment by QuickNET-Tech** [comment]
> Any more info on that?

It's been shared around the internet, menu devs have picked up on it, expect to see it in P2Cs ("pay to cheat"s aka paid mod menus) sometime soon as there's no way they won't add this, it's too valuable to not only themselves when developing but also to (potential) customers.

**Comment by patrickvrl** [comment]
> **Anyone here have download link gta5.exe (1.53) for steam?**
> 
> I want to port it to R* Launcher Version

i have all the gta versions to PC, if someone needs the exe, just quote me
right now i don't have the steam version installed but my friend has it

**Comment by rfoodxmodz** [comment]
> > **Anyone here have download link gta5.exe (1.53) for steam?**
> > I want to port it to R* Launcher Version
> 
> i have all the gta versions to PC, if someone needs the exe, just quote me
> right now i don't have the steam version installed but my friend has it

ok I need the steam gta5.exe
my twitter is rfoodxmodz or give me ur social account

**Comment by miloscosovic11** [comment]
0.0 its all coming together

**Comment by QuickNET-Tech** [comment]
Here's some sigs if anyone is planning to fork this into a platform independent version or something.

netcat_insert_dedupe_addr:
`4C 89 44 24 18 57 48 83 EC ? 48 8B FA` SUB `0x5`

netcat_insert_direct:
`3B D1 B0 01 0F 4E D1` SUB `0x11` RIP `4`

strlen_addr:
`48 3B C1 4C 8B C6` SUB `0x11` RIP `4`

**Comment by PDDStudio** [comment]
A short question from my side, (why) is the `gta5.exe` different depending on which platform (launcher; not version) you use to launch the game?
I would've expected these two things to be separate, but I'm not much into how Windows handles such stuff & all that. 

You end up in GTA anyways (which is where you hook the functions if I got it right), so why would you have to do a launcher-specific version (or a generic solution which can handle all launchers) at all?

I'm trying to understand the relations between those two, any help is appreciated :)

**Comment by QuickNET-Tech** [comment]
> A short question from my side, (why) is the `gta5.exe` different depending on which platform (launcher; not version) you use to launch the game?
> I would've expected these two things to be separate, but I'm not much into how Windows handles such stuff & all that.
> 
> You end up in GTA anyways (which is where you hook the functions if I got it right), so why would you have to do a launcher-specific version (or a generic solution which can handle all launchers) at all?
> 
> I'm trying to understand the relations between those two, any help is appreciated :)

The steam version is different from the RGL and EGS versions, why, I'm not really sure, I'd also like to know why R* have done this.

**Comment by PDDStudio** [comment]
> The steam version is different from the RGL and EGS versions, why, I'm not really sure, I'd also like to know why R* have done this.

Thanks for the info, maybe someone else can go a bit more into detail here.

**Comment by rfoodxmodz** [comment]
GTAO Booster DLL Files for Rockstar Launcher & Steam
https://twitter.com/rfoodxmodz/status/1366760443193212932?s19

Thank you @brchoose for gta5.exe
Credit @tostercx

**Comment by miloscosovic11** [comment]
Youre a king mane, thank you.

**Comment by deton24** [comment]
If you have a problem with downloading the file on Mobile, open it in
external browser, not in Twitter app, and make sure ~2 ads opened in
separate tabs, otherwise the download button doesn't react.

wt., 2 mar 2021, 16:38 użytkownik miloscosovic11 <notifications@github.com>
napisał:

**Comment by AmyrAhmady** [comment]
> > The steam version is different from the RGL and EGS versions, why, I'm not really sure, I'd also like to know why R* have done this.
> 
> Thanks for the info, maybe someone else can go a bit more into detail here.

Steam version contains steam stuff built in using Steam SDK (like steam api and overlay and what not) which obviously changes position of instructions in output binary file, while Rockstar Launcher one doesn't need it
By having instructions being moved to other places, this means memory addresses are also changed (hardcoded mem addresses in this repository's code for example)

I don't know what's with Epic Games version cause I've never had it installed since I'm really a fan of EGS, so I don't know if it's different than RGL version :)

**Comment by PDDStudio** [comment]
> GTAO Booster DLL Files for Rockstar Launcher & Steam
> https://twitter.com/rfoodxmodz/status/1366760443193212932?s19
> 
> Thank you @brchoose for gta5.exe
> Credit @tostercx

Could you create one for EGL as well? And be able to share the source code with the changes? That would be nice

**Comment by ahmettmertt** [comment]
> GTAO Booster DLL Files for Rockstar Launcher & Steam
> https://twitter.com/rfoodxmodz/status/1366760443193212932?s19
> 
> Thank you @brchoose for gta5.exe
> Credit @tostercx

Why no source code?

**Comment by PCPisChill** [comment]
I made a pull request with offsets for Rockstar Launcher/Social Club & Epic Games version (same offsets), see: #16

**Comment by patrickvrl** [comment]
> I made a pull request with offsets for Rockstar Launcher/Social Club & Epic Games version (same offsets), see: #16

Nice man, I already built it with the EGL fix, if anyone wants to download it. [Mediafire link](https://www.mediafire.com/file/fqu7q7v3fir8963/GTAO_Booster+EGL.dll/file)

**Comment by QuickNET-Tech** [comment]
Made a version that should work on any game version and it's open source.
Massive thanks to tostercx once again!
https://github.com/QuickNET-Tech/GTAO_Booster_PoC

**Comment by deton24** [comment]
Could you consider building the DLL for casual users as well, e.g. on
releases page?
It might get more popular and published e.g. on PcGamingWiki.
Nice work everyone.

śr., 3 mar 2021, 15:07 użytkownik QuickNET-Tech <notifications@github.com>
napisał:

**Comment by QuickNET-Tech** [comment]
> Could you consider building the DLL for casual users as well, e.g. on
releases page?

Sure, here ya go!
https://github.com/QuickNET-Tech/GTAO_Booster_PoC/releases/tag/v1.0.0

**Comment by deton24** [comment]
Thank you! I passed the info further.
If you'll have anything important to add, e.g. any info on official patch will be given, here's the entry about the fix on Wiki:
https://www.pcgamingwiki.com/wiki/Grand_Theft_Auto_V#Very_slow_loading_of_GTA:_Online

**Comment by tostercx** [comment]
@QuickNET-Tech thanks, redirecting everyone to you for builds in the readme
