### ISSUE TITLE
Injector

### ISSUE THREAD

**Issue by Misio12320** [tostercx/GTAO_Booster_PoC#20]
Hi. Which injector use and its safe?

**Comment by emanueleriboldi** [comment]
Xenos wich is downloadable from: https://mega.nz/file/zNs2wAAD#2ZKEp_78Vd42M-mat6pL5AhK6IN7T9MUgUZsyQh8vao

**Comment by needkg** [comment]
Xenos Release> https://github.com/DarthTon/Xenos/releases
