### ISSUE TITLE
My issues are open

### ISSUE THREAD

**Issue by QuickNET-Tech** [tostercx/GTAO_Booster_PoC#24]
Not sure how else to get ahold of you tostercx, so I'll just say it here I guess.
My issues being closed wasn't your fault.
Being a bit of a GitHub newb I forgot to open them on the fork. 
They're open now, thanks for bringing it to my attention. :D

**Comment by tostercx** [comment]
Ohh, my bad! Have my day job to do among other things and had no idea where to send everyone so I dumped them on you without asking. Assumed the worst ^^;

Gonna correct the readme.
