### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by TheSheep-stack** [tostercx/GTAO_Booster_PoC#25]
The Game Crashes while loading GTA Online after injecting the DLL

**Comment by QuickNET-Tech** [comment]
Which DLL? You build this yourself or are you using mine/someone else's?

**Comment by BHY4A** [comment]
When I'm playing with my friends, Online seems like freezes (not crash). Freezes at the end of the race, on the heist, when spinning the lucky wheel in the casino, etc. When loading fully, without dll, online works properly.
I'm using QuickTechNet's release.

**Comment by TheSheep-stack** [comment]
I accidently built the steam version. Universal works
