### ISSUE TITLE
What decompiler software do you use?

### ISSUE THREAD

**Issue by shanlanCoding** [tostercx/GTAO_Booster_PoC#34]
>Having borrowed my friend’s completely legitimate copy of the industry-standard disassembler

I saw in your blog that you used a legal decompiler, but I want to know what it is? thank you.

**Comment by tostercx** [comment]
It's a joke :) I used IDA Pro + Hex Rays

The price is pretty high and quickly becomes ridiculous if you need more than one OS/architecture https://www.hex-rays.com/cgi-bin/quote.cgi/products

So unless your company buys it for you it's out of most individual's reach.

If you're just starting out I suggest ghidra: https://ghidra-sre.org/

It's free! The decompiler isn't as good as IDA's but it's good enough for hobby use (and probably most professional uses too). Ghidra wasn't released yet when I started out so I just haven't bothered to learn it yet.

**Comment by shanlanCoding** [comment]
> It's a joke :) I used IDA Pro + Hex Rays
> 
> The price is pretty high and quickly becomes ridiculous if you need more than one OS/architecture https://www.hex-rays.com/cgi-bin/quote.cgi/products
> 
> So unless your company buys it for you it's out of most individual's reach.
> 
> If you're just starting out I suggest ghidra: https://ghidra-sre.org/
> 
> It's free! The decompiler isn't as good as IDA's but it's good enough for hobby use (and probably most professional uses too). Ghidra wasn't released yet when I started out so I just haven't bothered to learn it yet.

Thank you. You are really very enthusiastic !
