### ISSUE TITLE
collab

### ISSUE THREAD

**Issue by Ffannik** [tostercx/GTAO_Booster_PoC#37]
@tostercx I'm working on a games-related project. Can't tell you more details here. But I think you might be interested. It has the potential for becoming the next big thing in the game industry. It's not hard. It's doable. I'm just looking for dedicated and interested teammates. Please contact me via fannik#3371 on discord. If you aren't on discord tell me, I can then provide you with an email address.

**Comment by tostercx** [comment]
Hey, added you on discord.
